/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bdl;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.Map;
import javax.persistence.EntityManagerFactory;
import javax.persistence.criteria.AbstractQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import presistt.Pembayaran;
import presistt.Penyewaan;

/**
 *
 * @author Irkhamnawan
 */
public class penyewaan extends javax.swing.JPanel {

    /**
     * Creates new form bukuu
     */
    
    ArrayList<Penyewaan> dataSewa;
    ArrayList<Pembayaran> dataByr;
//    boolean sm = true;
    public penyewaan() {
        initComponents();
        tampilkan();
        tampilkan2();
    }
    
    private void tampilkan() {
        EntityManager entityManager = Persistence.createEntityManagerFactory("bdlPU").createEntityManager();
        entityManager.getTransaction().begin();
        Query query = entityManager.createQuery("SELECT p FROM Penyewaan p");
        List<Penyewaan> results = query.getResultList();
        entityManager.getTransaction().commit();
//        
        DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
        tbl.setRowCount(0);
        for(Penyewaan p : results){
            Object[] ob = new Object[7];
            ob[0] = p.getIdPenyewaan();
            ob[1] = p.getIdPelanggan().getIdPelanggan();
            ob[2] = p.getIdPegawai().getIdPegawai();
            ob[3] = p.getTotalBiaya();
            ob[4] = p.getTanggalPenyewaan();
            ob[5] = p.getTanggalKembali();
            ob[6] = p.getJumlahHari();
            tbl.addRow(ob);
        }
        entityManager.close();        
    }
    
    private void tampilkan2() {
        EntityManager entityManager = Persistence.createEntityManagerFactory("bdlPU").createEntityManager();
        entityManager.getTransaction().begin();
        Query query = entityManager.createQuery("SELECT p FROM Pembayaran p");
        List<Pembayaran> results = query.getResultList();
        entityManager.getTransaction().commit();
//        
        DefaultTableModel tbl = (DefaultTableModel) jTable2.getModel();
        tbl.setRowCount(0);
        for(Pembayaran py : results){
            Object[] ob = new Object[6];
            ob[0] = py.getNoNota();
            ob[1] = py.getIdPenyewaan().getIdPenyewaan();
            ob[2] = py.getTanggalPembayaran();
            ob[3] = py.getTotalPembayaran();
            ob[4] = py.getStatusPembayaran();
            ob[5] = py.getSisaBayar();
            tbl.addRow(ob);
        }
        entityManager.close();        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 229, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(220, 167, 163));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Penyewaan", "ID Pelanggan", "ID Pegawai", "Total Biaya", "Tanggal Sewa", "Tanggal Kembali", "Jumlah Hari"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 67, -1, 143));

        jButton1.setBackground(new java.awt.Color(230, 149, 128));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("INPUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 119, 80, 30));

        jButton5.setBackground(new java.awt.Color(230, 149, 128));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("PRINT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 80, 30));

        jTable2.setBackground(new java.awt.Color(220, 167, 163));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No Nota", "ID Penyewaan", "Tanggal Pembayaran", "Total Bayar", "Status", "Sisa Pembayaran"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 239, -1, 128));

        jButton7.setBackground(new java.awt.Color(230, 149, 128));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("BAYAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 80, 30));

        jButton6.setBackground(new java.awt.Color(230, 149, 128));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("PRINT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 80, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inputSewa is = new inputSewa(jTable1);
        is.setVisible(true);
        tampilkan2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
        EntityManager entityManager = Persistence.createEntityManagerFactory("bdlPU").createEntityManager();
        entityManager.getTransaction().begin();

        int row = jTable1.getSelectedRow();
        String tabel_klik = (jTable1.getModel().getValueAt(row, 0).toString());

    // Ubah kode di bawah ini untuk mencari data yang diinginkan
    Penyewaan p = entityManager.find(Penyewaan.class, tabel_klik);
    if (p != null) {
        String idPenyewaan = p.getIdPenyewaan();
        String idPelanggan = p.getIdPelanggan().getIdPelanggan();
        String idPegawai = p.getIdPegawai().getIdPegawai();
        double totalBiaya = p.getTotalBiaya();
        Date tanggalPenyewaan = p.getTanggalPenyewaan();
        Date tanggalKembali = p.getTanggalKembali();
        String jumlahHari = p.getJumlahHari();
    }

    entityManager.getTransaction().commit();
} catch (Exception e) {
    // Handle exceptions appropriately
}
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String reportPath = "src/bdl/reportByr.jrxml";
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("bdlPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        
        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Pembayaran> cq = cb.createQuery (Pembayaran.class);
        Root<Pembayaran> bok = cq.from(Pembayaran.class);
        cq.select(bok);
        
        TypedQuery<Pembayaran> q = em.createQuery(cq);
        List<Pembayaran> list = q.getResultList();
        Query query = em.createQuery("SELECT p FROM Pembayaran p");
        List<Penyewaan> result = query.getResultList();
        
        JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource (result);
        
        
        try {
            // TODO add your handling code here:
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, dataSource);
            JasperViewer vw = new JasperViewer (jp, false);
            vw.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        em.getTransaction().commit();
        em.close();
        emf.close();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        inputByr ik = new inputByr(jTable2);
        ik.setVisible(true);
        tampilkan2();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String reportPath = "src/bdl/reportPny.jrxml";
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("bdlPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        
        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Penyewaan> cq = cb.createQuery (Penyewaan.class);
        Root<Penyewaan> bok = cq.from(Penyewaan.class);
        cq.select(bok);
        
        TypedQuery<Penyewaan> q = em.createQuery(cq);
        List<Penyewaan> list = q.getResultList();
        Query query = em.createQuery("SELECT p FROM Penyewaan p");
        List<Penyewaan> result = query.getResultList();
        
        JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource (result);
        
        
        try {
            // TODO add your handling code here:
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, dataSource);
            JasperViewer vw = new JasperViewer (jp, false);
            vw.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Penyewaan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        em.getTransaction().commit();
        em.close();
        emf.close();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
